README.md

Fix link to example in README.md

---

.circleci/config.yml
README.md
package-lock.json
package.json

Added badges for `npm` and `codecov`

Add codecov and npm badges

---

CONTRIBUTING.md
README.md
TROUBLESHOOTING.md
cypress/integration/smoke.test.ts

Added contributing and troubleshooting guides

[SDK-1704] Add contributing and troubleshooting guides

---

Jenkinsfile

Add a Jenkinsfile to manage deployments.

Add Jenkinsfile to manage deployments.

---

examples/cra-react-router/src/App.tsx
examples/cra-react-router/src/ProtectedRoute.tsx
examples/cra-react-router/src/index.tsx

Added some comments to the Create React App Example for users that want to use Hash Routing `https://www.exaple.com/#/my-route`

Add some comments to the CRA example for hash routing

---

README.md

Update QS link

---

.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/report-a-bug.md
FAQ.md
README.md

Add issue templates

---

package.json

[SDK-2104] Update peerDeps to account for react 17

---

package-lock.json
package.json

https://github.com/auth0/auth0-spa-js/releases/tag/v1.13.0
https://github.com/auth0/auth0-spa-js/releases/tag/v1.13.1
fixes #124

Bump spa js to 1.13.1

---

examples/users-api/package-lock.json
examples/users-api/package.json
jest.config.js
package-lock.json
package.json

Fixing a couple of dependabot alerts for `axios` and `node-notifier`

Fix some dependabot alerts

---

EXAMPLES.md
package-lock.json
package.json
src/auth0-provider.tsx

- Update SPA JS
- Make sure SPA JS organization docs appear in auth0-react docs
- Add an organizations example

Update SPA JS and add orgs example

---

package-lock.json
package.json

See https://github.com/auth0/auth0-spa-js/releases/tag/v1.17.1

Bump SPA JS to 1.17.1

---

.circleci/config.yml
.shiprc
package.json

Add `.shiprc` to run docs on release script
Add CircleCI publishing job

[SDK-2731] Prepare for automated releasing

---

CHANGELOG.md
docs/classes/errors.oautherror.html
docs/interfaces/auth0_context.auth0contextinterface.html
docs/interfaces/auth0_context.redirectloginoptions.html
docs/interfaces/auth0_provider.auth0provideroptions.html
docs/interfaces/with_auth0.withauth0props.html
docs/interfaces/with_authentication_required.withauthenticationrequiredoptions.html
docs/modules/auth0_context.html
docs/modules/auth0_provider.html
docs/modules/use_auth0.html
docs/modules/with_auth0.html
docs/modules/with_authentication_required.html
package-lock.json
package.json

**Added**
- Bump Auth0-SPA-JS to 1.18.0 [\#279](https://github.com/auth0/auth0-react/pull/279) ([adamjmcgrath](https://github.com/adamjmcgrath))

Release v1.8.0

---

src/auth0-provider.tsx

Aligns with config for underlying `auth0-spa-js` config.
https://auth0.github.io/auth0-spa-js/interfaces/auth0clientoptions.html

Add connection property to Auth0ProviderOptions

---

EXAMPLES.md

Small fix to broken link on the EXAMPLES.md page. Noticed while going through the examples.
None
Manual testing

docs: Update EXAMPLES.md link for accessing protected APIs with access token

---

MIGRATION_GUIDE.md

Adds the migration guide for the v2 upgrade

[SDK-3825] Add migration guide

---

README.md

Typedoc changes the structure of some URLs so we need to amend the readme links for that

[SDK-3850] Update links to api reference

---

MIGRATION_GUIDE.md

Updated [v2 Migration Guide](https://github.com/auth0/auth0-react/blob/master/MIGRATION_GUIDE.md) to include changes reflecting needing to move `audience` parameter to `authorizationParams`. While there is more that moved to `authorizationParams`, a lot of people will likely need to do this as well, thereby saving them time in figuring that out.
NA
NA

Update v2 Migration Guide

---

MIGRATION_GUIDE.md

Ensures https://github.com/auth0/auth0-react/pull/481 gets merged into master instead of beta.

Add authorizationParams.audience to Migration Guide(#481)

---

EXAMPLES.md

origanization and invitation is supposed to be set on the authorizationParams as of v2.
Closes #492

Update Examples for v2

---

src/auth0-provider.tsx

Update jsdoc for Auth0Provider redirect_uri

---

MIGRATION_GUIDE.md

Update MIGRATION_GUIDE to include withAuthenticationRequired

---

package-lock.json
package.json

Bumping SPA-JS before cutting a release.

Bump auth0-spa-js

---

.husky/pre-commit
package.json

https://github.com/auth0/auth0-react/pull/530 updated husky from 4 -> 8
https://typicode.github.io/husky/#/?id=migrate-from-v4-to-v8

Migrate to Husky 8

---

README.md

Updating README documentation example code. The `returnTo` parameter has been moved into `logoutParams`.
[#550 ](https://github.com/auth0/auth0-react/issues/550)
N/A

fix: Updating logout function on README example code

---

.github/ISSUE_TEMPLATE/Bug Report.yml
.github/ISSUE_TEMPLATE/Feature Request.yml
.github/ISSUE_TEMPLATE/config.yml
.github/workflows/browserstack.yml
.github/workflows/codeql.yml
.github/workflows/integration.yml
.github/workflows/publish.yml
.github/workflows/semgrep.yml
.github/workflows/snyk.yml
.github/workflows/test.yml
EXAMPLES.md
FAQ.md
README.md
TROUBLESHOOTING.md
docs/index.html

Renames references from master to main.
https://github.com/auth0/auth0-angular/issues/469

Update references from master to main branch

---

.github/dependabot.yml
.github/workflows/publish.yml

* Adds `registry-url` to publish node job per auth0/lock/pull/2445
* Removes publishing to GitHub packages
* Adds npm dependabot config back
> Include any links supporting this change such as a:
>
> - GitHub Issue/PR number addressed or fixed
> - Auth0 Community post
> - StackOverflow post
> - Support forum thread
> - Related pull requests/issues from other repos
>
> If there are no references, simply delete this section.
> Describe how this can be …

Update actions and dependabot config

---

src/index.tsx

Exports errors from Auth0-SPA-JS that were not yet exported.
#636

Export all errors from SPA-JS

---

src/index.tsx

Ensure GenericError is also exported.
Closes #643

Export GenericError

---

CHANGELOG.md
package-lock.json
package.json

**Fixed**
- Revert "Make OAuthError extend GenericError" [\#646](https://github.com/auth0/auth0-react/pull/646) ([frederikprijck](https://github.com/frederikprijck))

Release v2.2.3

---

.github/workflows/release.yml

This permission is needed in order to publish using `--provenance`
> Include any links supporting this change such as a:
>
> - GitHub Issue/PR number addressed or fixed
> - Auth0 Community post
> - StackOverflow post
> - Support forum thread
> - Related pull requests/issues from other repos
>
> If there are no references, simply delete this section.
> Describe how this can be tested by reviewers. Be specific about anything not tested and reasons why. If this library has unit and/or integration testing, tests should be added for new functionality and existing tests should complete without errors.
>
> Please include any manual steps for testing end-to-end or functionality not covered by unit/integration tests.
>
> Also include details of the environment this PR was developed in …

Request id-token permission

---

.github/actions/tag-exists/action.yml
.github/workflows/release.yml

The tag-exists action was not working due to the fact that it was trying to read from a step that did not exist.
Without these changes, it would always 404 and act as if the tag doesn't exist.

Ensure tag-exists action works as intended

---

src/auth0-provider.tsx

Fixed a typo in the documentation of Auth0Provider.

Fixed typo in Auth0Provider docs

---

.github/workflows/browserstack.yml
.github/workflows/integration.yml
.github/workflows/semgrep.yml
.github/workflows/snyk.yml

ci: changed pull_request_target to pull_request and removed the authorize step

---

EXAMPLES.md

> Describe the purpose of this PR along with any background information and the impacts of the proposed change. For the benefit of the community, please do not assume prior context.
>
> Provide details that support your chosen implementation, including: breaking changes, alternatives considered, changes to the API, etc.
>
> If the UI is being changed, please provide screenshots.
> Include any links supporting this change such as a:
>
> - GitHub Issue/PR …

Test Reversing Labs
