README.md
__tests__/with-authentication-required.test.tsx
src/index.tsx
src/with-authentication-required.tsx
typedoc.js

There are some cases where just the `location.pathname` is not enough information for the user to be returned to the url they were redirected to the login page from. eg hashrouting
Allow the `returnTo` param to be customised as a string or a method to handle these cases, eg for hash routing:
```js
// A typical hash route will look like http://localhost:3000/#/users
withAuthenticationRequired(Users, {
returnTo: () => window.location.hash.substr(1) // '/users'
})
```
Also allow the user to pass `RedirectLoginOptions` to `loginWithRedirect` in case they want to add additional `appState`
https://github.com/auth0-samples/auth0-vue-samples/issues/100 (A Vue example, but the same applies to React)
https://reacttraining.com/react-router/web/api/HashRouter

Add extra options to withAuthenticationRequired

---

README.md
examples/cra-react-router/src/Nav.tsx
examples/gatsby-app/src/components/Nav.js
examples/nextjs-app/components/Nav.js
src/auth0-context.tsx
static/index.html

We recommend that people provide the `returnTo` argument to `logout`, otherwise they roll the dice with being returned to the first "allowed logout url" in the application's settings.

Update examples to have `returnTo` option set in logout

---

README.md

Clear up some confusion about the `auth0` prop in Class components 
fixes #54

Clarify `auth0` prop from `withAuth0`

---

examples/users-api/package-lock.json
examples/users-api/package.json
examples/users-api/server.js

This change relates to the recent express-jwt release.
It only impacts the sample app. I'm not sure if any changelog labels should go with it.
See https://github.com/advisories/GHSA-6g6m-m6h5-w9gf.

Update sample using express-jwt v6

---

src/auth0-context.tsx
src/auth0-provider.tsx

`Auth0Client` provides a second argument `config` for `loginWithPopup` function. 
Unfortunately in `auth0-react` the second argument has been omitted.
This change just redirects config argument to `Auth0Client` so no testing is needed.

Add config argument to loginWithPopup

---

examples/gatsby-app/src/components/Nav.js

The tests use the dev server (`npm start`)
fixes #83

Fix `npm run build` on Gatsby example

---

package-lock.json
package.json

The SDK was a few patches behind, and while the codecov command was running successfully, the uploaded files contained errors. This newer version also fixes a vulnerability. 
- See: https://github.com/codecov/codecov-node#change-log
- Snyk report: https://snyk.io/vuln/npm:codecov@3.7.0

Update codecov and fix reports

---

package-lock.json
package.json

Fixes a few security vulnerabilities reported for lodash and serialize-javascript.
First commit 
```
> npm audit fix
...
fixed 4737 of 4738 vulnerabilities in 1070 scanned packages
1 package update for 1 vulnerability involved breaking changes
```
Second commit, fixes a vulnerability reported by dependabot. See "testing" section below.
```
> npm install --save-dev rollup-plugin-terser@7.0.0
found 0 vulnerabilities
```
- https://github.com/advisories/GHSA-p6mc-m468-83gw
- https://github.com/advisories/GHSA-hxcc-f52p-wc94
I ran the unit tests, `npm run build` and `npm run start` (both commands using rollup); and tried the demo locally. Seems to be OK but you might want to double check @adamjmcgrath .

Upgrade dependencies to latest

---

package.json

Support react and react-dom 16.11.
https://github.com/auth0/auth0-react/issues/96
I tested by changing these lines
https://github.com/auth0/auth0-react/blob/master/package.json#L75-L76
to 
```
"react": "~16.11.0",
"react-dom": "~16.11.0",
```
and running `npm test` (these all pass)
I reverted this because I figured it's better to test with 16.13 normally. Is there a different approach you'd like to take?
I tried setting up the integration tests but I ran into these kinds of errors:
```
Module not found: Can't resolve '@auth0/auth0-react' in ' ...
```

Support react v16.11 (#96)

---

__tests__/auth-provider.test.tsx
__tests__/with-authentication-required.test.tsx
src/auth0-provider.tsx

Duplicated getUser call removed from Auth0Provider, tests that depend on isAuthenticated Auth0Client method are updated.
https://github.com/auth0/auth0-react/issues/103
Test are updated and passing.

duplicated getuser call removed

---

__tests__/utils.test.tsx
src/utils.tsx

Because SPA JS always sends a `state` param to `/authorize`, we can always assume that a valid redirect callback will contain both `state` and `code`. 
Doing this will reduce the chance of collisions when the application is using the `code` param for something unrelated to auth.
Might mitigate some cases of #75

[SDK-1927] Check for state param in callback url

---

examples/cra-react-router/src/index.tsx
src/index.tsx

Export `AppState` type so it can be used in custom `onRedirectCallback`'s
See https://github.com/auth0/auth0-react/blob/a4c5f675217ebfbd36b8c2245b7f1a36c2db4b0d/examples/cra-react-router/src/index.tsx#L4-L11
Fixes #119

Export AppState type for custom onRedirectCallback's

---

package-lock.json
package.json
rollup.config.js

When running `npm run build`, rollup will output information about our bundle size. This is a first step to get better insight into our bundle size.

Add bundle analysis output when running build

---

src/auth0-context.tsx
src/auth0-provider.tsx

Add workaround config argument to getAccessTokenWithPopup to work with iOS, similar to loginWithPopup.
https://github.com/auth0/auth0-spa-js/pull/368

Add config argument to getAccessTokenWithPopup

---

src/with-authentication-required.tsx

> React Fast Refresh is now used by default in Next.js 10. RFR require named components, otherwise it will reload whole page. This is a small fix that replaces unnamed arrow function with named function.
This can be tested by bootstraping next.js project and setting up this package. Wrapping any page export with `withAuthenticationRequired` should result in smooth content refresh after change.
Btw: it would be cool to get this accepted as hacktoberfest PR, thanks!

fix: add react fast refresh support

---

__tests__/auth-provider.test.tsx
src/auth0-provider.tsx

~~(will base on `master` after #146 is merged)~~
Memoizing the auth methods means that downstream components that use them in dependent keys of other hooks wont get unnecessary updates when auth state changes.
*Easier to review if you hide whitespace changes https://github.com/auth0/auth0-react/pull/150/files?w=1
Fixes #131

[SDK-2106] Memoize auth methods

---

__tests__/auth-provider.test.tsx
examples/cra-react-router/src/ProtectedRoute.tsx
examples/gatsby-app/src/components/ProtectedRoute.js
examples/gatsby-app/src/pages/index.js
package.json
src/auth0-provider.tsx
src/reducer.tsx

- Fix issue where CI wasn't picking up failing Gatsby and CRA tests
- Any updates in the provider will trigger a new render of child components so only dispatch the user update when the `updated_at` date has changed (this should satisfy #135)
- Fix the Gatsby and CRA examples, `ProtectedRoute` shouldn't remount every time the app rerenders
Fixes #155

Remove unintential render after each getAccessToken* call

---

src/auth0-provider.tsx

Fuelled by [this issue on the React samples](https://github.com/auth0-samples/auth0-react-samples/pull/215), this PR adds more context to the `cacheLocation` property with a link off to read more about the storage options. This makes sense, as the docs also carry a warning about local storage that we're not otherwise relaying here.

Add link to info about storage options on cacheLocation

---

src/auth0-provider.tsx

The types, used internally, are configured incorrectly. This works fine because of the fact that the types are configured to allow any unknown property to be set.
Switching the types should not affect anyone using the SDK.

Update Types for LoginWithRedirect

---

__tests__/ssr.test.tsx
src/auth-state.tsx

I originally thought `isLoading` should initialize as `false` when doing SSR, the logic being that the SDK will never start loading during SSR so `isLoading` didn't make sense to be `true`
However, the output of SSR rendering is rendered on the client, to be hydrated, so a client will expect it to be initialised as `true`. If it's `false`, then immediately hydrated as `true` you get `Warning: Expected server HTML to contain a matching <div> in <div>.` because it's been rendered in a different state that the `ReactDom.hydrate` is expecting.
Whilst this will change initial rendering behaviour, it shouldn't break anyone - just remove the warning.
fixes #182 
I've changed the SSR tests to use `ReactDOMServer.renderToString` rather than `renderHook` because `renderHook` still expects to be …

isLoading should default to true even when doing SSR

---

__tests__/auth-provider.test.tsx

I merged a PR from a fork with a broken test - just fixing the build
`buildAuthorizeUrl` accepts `redirectUri` and calls the SPA JS client with `redirect_uri `

Fix buildAuthorizeUrl tests

---

.circleci/config.yml
examples/cra-react-router/package.json
examples/cra-react-router/tsconfig.json

If we skip integration tests on forked PRs we can enable the build and run the unit tests on forked PRs
Bumped `react-scripts` so we can get rid of the patch for facebook/create-react-app#8845
https://github.com/auth0/nextjs-auth0/pull/341

Skip integration tests on forked PRs

---

__tests__/auth-provider.test.tsx
src/auth0-provider.tsx
src/reducer.tsx

Updates to the `user` from the Authorization Server should not require updates to the `getAccessToken*` memoized methods. (Thanks for the suggestion @xepps)
fixes #210 
- add a side effect that depends on `getAccessTokenSilently`, eg `useEffect(() => console.log('changed'), [getAccessTokenSilently])`
- login
- make a change to your user (eg name) in the tenant dashboard
- call `getAccessTokenSilently({ ignoreCache: true })`
- anything rendering the user name should change, but the side effect should not be called

Updates to user should not update memoized getAccessToken* methods

---

__tests__/auth-provider.test.tsx
src/auth0-provider.tsx
src/reducer.tsx

We should attempt to update the auth state after `getAccessToken*` methods fail, to handle the use case where the user may have been logged out in another tab.
fixes: #218 
- Add the `ignoreCache: true` option `getAccessTokenSilently` in the [playground](https://github.com/auth0/auth0-react/blob/master/static/index.html#L55)
- Run the playground `npm start` and visit http://localhost:3000
- Login to the app
- Open another tab and visit http://localhost:3000
- Both tabs should show the user as logged in
- Logout of the second tab
- Click `Get access token` in the first tab
- Both tabs should show the user as logged out

Update auth state on fail

---

README.md
examples/cra-react-router/src/Nav.tsx
src/auth-state.tsx
src/auth0-context.tsx
src/use-auth0.tsx

Adds generic type parameter to `useAuth0` to specify type of `user` (see #228 for feature request)
```ts
const { user } = useAuth0<{ name: string; }>();
user.name // string
```
This parameter is optional and will use the already existing `User` type if not provided
Closes #228
Closes #201 
I tried to unit test this but I'm not sure of the correct way to pass type params to a hook through `renderHook`
You can see this in-use in the Create React App example

Add TUser type param to useAuth0 hook

---

__tests__/auth-provider.test.tsx
__tests__/utils.test.tsx
examples/cra-react-router/src/Nav.tsx
src/utils.tsx

PKCE will always provide a `state` when it provides an `error` param in the callback, so we can check for that to prevent the `error` param clashing with other uses of the `error` param.
This matches `auth0-angular` https://github.com/auth0/auth0-angular/blob/master/projects/auth0-angular/src/lib/auth.service.ts#L317-L318
fixes: #225

[SDK-2522] Check for state along with error param

---

__tests__/auth-provider.test.tsx
src/auth0-context.tsx
src/auth0-provider.tsx
src/reducer.tsx

This PR exposes the `handleRedirectCallback` function from `auth0-spa-js`,
which has been abstracted away until now. Exposing this enables a use case for
hybrid mobile (Capacitor, Cordova, etc) apps to be able to work end-to-end.
fixes #222

[SDK-2541] Expose handleRedirectCallback from auth0-spa-js

---

__tests__/auth-provider.test.tsx
__tests__/auth-reducer.test.tsx
__tests__/with-authentication-required.test.tsx
src/auth-state.tsx
src/auth0-context.tsx
src/index.tsx
src/reducer.tsx
src/use-auth0.tsx
src/with-authentication-required.tsx

This PR is a proposal for using [`User` class defined in auth0-spa-js](https://github.com/auth0/auth0-spa-js/blob/master/src/global.ts#L510-L532) instead of existing User type of `any`. 
```diff
- export type User = any;
+ import { User } from '@auth0/auth0-spa-js';
export interface AuthState<TUser extends User = User> {
error?: Error;
isAuthenticated: boolean;
isLoading: boolean;
user?: TUser;
}
``` 
I think that this PR would enhance …

feat: use User class defined in auth0-spa-js

---

README.md

This PR changes the relative paths to our markdown files to use absolute paths. 
Doing so would ensure the paths still work from our hosted API docs.
The downside here is that it will always point to master, but I believe that is still better as opposed to having 404 links on our API docs.
See: #242

Change relative links to absolute links

---

__tests__/auth-provider.test.tsx
package-lock.json
package.json
src/auth0-provider.tsx
src/index.tsx

This PR upgrades `@auth0/auth0-spa-js` to [v1.16.0](https://github.com/auth0/auth0-spa-js/releases/tag/v1.16.0) and exposes the new custom cache option.
https://github.com/auth0/auth0-spa-js/releases/tag/v1.16.0
https://github.com/auth0/auth0-spa-js/pull/743

[SDK-2603] Expose custom caching options from Auth0 SPA SDK

---

CHANGELOG.md
docs/classes/errors.oautherror.html
docs/classes/index.user.html
docs/interfaces/auth0_context.auth0contextinterface.html
docs/interfaces/auth0_context.redirectloginoptions.html
docs/interfaces/auth0_provider.auth0provideroptions.html
docs/interfaces/index.getidtokenclaimsoptions.html
docs/interfaces/index.gettokensilentlyoptions.html
docs/interfaces/index.icache.html
docs/interfaces/index.logoutoptions.html
docs/interfaces/index.logouturloptions.html
docs/interfaces/index.popupconfigoptions.html
docs/interfaces/with_auth0.withauth0props.html
docs/interfaces/with_authentication_required.withauthenticationrequiredoptions.html
docs/modules/auth0_context.html
docs/modules/auth0_provider.html
docs/modules/index.html
docs/modules/use_auth0.html
docs/modules/with_auth0.html
docs/modules/with_authentication_required.html
package-lock.json
package.json

**Added**
- Bump SPA JS to 1.17.1 [\#270](https://github.com/auth0/auth0-react/pull/270) ([adamjmcgrath](https://github.com/adamjmcgrath))

Release v1.7.0

---

package-lock.json
package.json

Bumps SPA-JS to 1.18.0 to bring in the changes for that release (https://github.com/auth0/auth0-spa-js/blob/master/CHANGELOG.md#v1180-2021-09-15)

Bump Auth0-SPA-JS to 1.18.0

---

__tests__/with-authentication-required.test.tsx
src/with-authentication-required.tsx

Resolves https://github.com/auth0/auth0-react/issues/309

Avoid potential multiple invocations of loginWithRedirect

---

__tests__/auth-provider.test.tsx
src/auth0-provider.tsx

We've seen a few instances where the context value in `Auth0Provider` needs to be memoized, as it is set to a new object value on each re-render and causes instances where we use the auth0 object in `useEffect` or `useCallback` to continuously re-evaluate.
Similar to https://github.com/auth0/auth0-react/pull/150, but now we're memoizing the whole object.
Added a new test to `auth0-provider.test` and ran without my changes:
```
FAIL …
```

Memoize context value in auth0-provider

---

__tests__/auth-provider.test.tsx
src/auth0-provider.tsx
static/index.html

`handleRedirectCallback` can only be called once, multiple invocations will result in "Invalid State" errors since the first invocation has the side effect of clearing the transaction state (SessionStorage or cookies) causing the second invocation to fail.
Because of this side effect `handleRedirectCallback` doesn't play well with the new Reusable State checks in StrictMode. 
When StrictMode remounts the `Auth0Provider`, the user hasn't logged in yet, `handleRedirectCallback` fails and the SDK initialises as logged out before the first `handleRedirectCallback` completes and initialises the SDK as logged in.
One symptom of this is that If you have code that detects if the user is logged out and redirects them to login (like `withAuthenticationRequired` does) you can get in an infinite loop …

Make sure handleRedirectCallback is only called once in StrictMode React 18

---

src/errors.tsx

Targeting ES5 breaks extending builtins classes. Namely, `new OAuthError() instanceof OAuthError` is false. The recommended workaround is to manually adjust the prototype.
https://github.com/Microsoft/TypeScript-wiki/blob/main/Breaking-Changes.md#extending-built-ins-like-error-array-and-map-may-no-longer-work
See also auth0-spa-js which implements the same fix: https://github.com/auth0/auth0-spa-js/blob/ab50548/src/errors.ts
This cannot be tested as the Jest config transpiles for ES6 which doesn't exhibit the issue. Changing Jest to use ES5 causes other issues (namely Istanbul coverage of the super call).
There is actually an existing test [`should convert OAuth error data to an OAuth JS error`](https://github.com/auth0/auth0-react/blob/05866c0/__tests__/utils.test.tsx#L48) which fails if …

Correctly extend Error for OAuthError

---

__tests__/auth-provider.test.tsx
src/auth0-provider.tsx

Enhance the `onRedirectCallback` prop in the `Auth0Provider` to expose the user, in this case, to conditionally redirect users.
For example:
Say a user is marked as a VIP in Auth0 as a means of enhancing that user's experience in the app. When the user logs in or creates an account as a VIP, they're redirected to a particular page and presented with special content as a VIP.
```js
// in Next.js...
import { Auth0Provider } from '@auth0/auth0-react';
import Router from 'next/router';
const onRedirectCallback = (appState, user) => {
const isVip = user['https://namespace.com/isVip'];  
if (isVip) return Router.replace(`/welcome/vip`);
Router.replace(appState && appState.returnTo ? appState.returnTo : window.location.pathname);
};
// ...
export default function App({ Component, pageProps }) { …
```

Enrich onRedirectCallback method with User object (#400)

---

__tests__/auth-provider.test.tsx
__tests__/helpers.tsx
__tests__/use-auth.test.tsx
__tests__/with-auth0.test.tsx
__tests__/with-authentication-required.test.tsx
src/auth0-context.tsx
src/auth0-provider.tsx
src/index.tsx
src/use-auth0.tsx
src/with-auth0.tsx
src/with-authentication-required.tsx

This adds support for multiple instances of `Auth0Provider` being used within an application, this is achieved by providing a `context` parameter (created using `React.createContext`) to the `Auth0Provider`, this same context can then be provided to `useAuth0`, `withAuth0`, and `withAuthenticationRequired` in order to access the authentication state and methods associated with that instance of `Auth0Provider`.
The choice to accept the `context` in the helpers was made to avoid users having to maintain their own versions of these that may deviate from the internal version. Whilst for `useAuth0` and `withAuth0` this was unlikely due to their simple-ness, `withAuthenticationRequired` is more complex so I figured that it was worth it.
#290
> Describe how this can be tested by reviewers. Be …

[SDK-3666] Support multiple providers

---

EXAMPLES.md
README.md
__tests__/auth-provider.test.tsx
__tests__/with-authentication-required.test.tsx
examples/cra-react-router/src/Nav.tsx
examples/cra-react-router/src/Users.tsx
examples/cra-react-router/src/index.tsx
examples/cra-react-router/src/use-api.ts
examples/gatsby-app/gatsby-browser.js
examples/gatsby-app/src/components/Nav.js
examples/gatsby-app/src/components/Users.js
examples/gatsby-app/src/hooks/use-api.js
examples/nextjs-app/components/Nav.js
examples/nextjs-app/hooks/use-api.js
examples/nextjs-app/pages/_app.js
examples/nextjs-app/pages/users.js
package-lock.json
package.json
src/auth0-context.tsx
src/auth0-provider.tsx
src/index.tsx
static/index.html

Updates the auth0-react source to be compatible spa-js v2 and fixes up the examples to work with those changes. I've also tried to reduce down the additional types in auth0-react in favour of the ones from auth0-spa-js where possible
This does not include any addition around the potential localOnly re-inclusion

[SDK-3784] Update to spa-js v2

---

browserstack.json
package-lock.json
package.json

Browserstack currently errors due to no auth params despite that being provided, trying to debug the issue.

Correct browserstack setup

---

.circleci/config.yml

Legacy images with the prefix “circleci/” were deprecated in 2021.
https://circleci.com/blog/announcing-our-next-generation-convenience-images-smaller-faster-more-deterministic/

chore(ci): use latest docker images

---

__tests__/auth-provider.test.tsx
src/reducer.tsx

Given that the user object is now cached in memory in auth0-spa-js the object is stable between calls to `getUser` if it does not update we can use object comparison to determine whether we need to update the state or not. This should solve cases like #347 where the user object is not updated when edited by rules

[SDK-3831] Do not check updated_at property now that user object is stable between calls

---

__tests__/auth-provider.test.tsx
package-lock.json
package.json
src/auth0-context.tsx
src/auth0-provider.tsx
src/index.tsx
src/with-authentication-required.tsx

Updates spa-js to 2.0.1 so that we pull in the `openUrl` update, updates the types so that `LogoutOptions` and `RedirectLoginOptions` are now from auth0-react and omit the `onRedirect` property, and also corrects the check around `openUrl` in light of the changes we made

Update spa-js and omit onRedirect from exported types

---

MIGRATION_GUIDE.md

The migration guide had a couple of issues with the fact that it didnt move the scope into `authorizationParams`.

Move scope into authorizationParams in migration guide

---

README.md

`ReactDOM.render` is deprecated in v18
See https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-client-rendering-apis
fixes #483

Update the code example for React 18

---

__tests__/auth-provider.test.tsx
src/auth0-provider.tsx
src/utils.tsx

With the release of Auth0-React v2, we have renamed redirectUri to redirect_uri and moved it into an authorizationParams property bag.
This has been called out multiple times to be problematic and causing bad DX, especially since the error logging on Auth0 server doesn't point in the correct direction.
We might want to add some deprecation strategy here to help people migrate instead, to ensure we increase DX again.
**Note**: this only patches the constructor and loginWithRedirect. All other methods in Auth0-React v1 were using `redirect_uri` and never even supported `redirectUri`.
#506

Support redirectUri again in a deprecated way

---

MIGRATION_GUIDE.md

Per #512 there is an issue with the suggested replacement for `claimCheck` we removed from `withAuthenticationRequired`. This fixes that issue by moving the usage of useAuth0 within a component created within the `withClaimCheck` HOC.
#512

Fix hooks usage within recommended replacement for claimCheck

---

MIGRATION_GUIDE.md

- The Migration guide calls the updated properties in `authorizationParams` kebab-case when they are snake_case.
Updates the description of updated properties in `authorizationParams` to 'snake-case' instead of 'kebab-case' in https://github.com/auth0/auth0-react/blob/master/MIGRATION_GUIDE.md#changes-to-parameter-casing

Update MIGRATION_GUIDE to reference snake_case

---

__tests__/auth-provider.test.tsx
__tests__/helpers.tsx
__tests__/with-authentication-required.test.tsx

Fixes some warnings occuring during running the tests:
- Not using `act` where we should use it.
- We have our own warnings which polute the test output. So whenever a warning is expected, I mocked the `console.warn` function instead, and verify it's been called.
- Reworked the test to verify a redirect message shows up now that act was added, which is async.
With the above changes, our console output when running the tests is a lot cleaner:

Fix warnings during tests

---

src/auth0-context.tsx
src/auth0-provider.tsx

Logout is async, so it shouldn't be marked as void, but `Promise<void>`, like we already do in the provider.
Closes #545

Fix inconsistent logout function types

---

EXAMPLES.md
package-lock.json
package.json

Add support for Organization Name by bumping Auth0-SPA-JS to v2.1.0.

Support Organization Name

---

package-lock.json
package.json

Bumps SPA-JS to v2.1.2 to include the fix for organizations.
https://github.com/auth0/auth0-spa-js/releases/tag/v2.1.2

bump auth0-spa-js to latest version

---

src/with-authentication-required.tsx

This PR fixes a typo in the docs and improves readability for the `withAuthenticationRequired` HOC

Fix typo and readability in with-authentication-required.tsx

---

.github/actions/integration/action.yml
.github/workflows/integration.yml
cypress.json
examples/users-api/server.js
package-lock.json
package.json

This pull request replaces our current CircleCI continuous integration suite for `auth0-react` with a new workflow using GitHub Actions.
Please see internal ticket SDK-4436.
This pull request replaces our continuous integration suite with one built in GitHub's native Actions ecosystem. It aligns with other migrations taking place across our repositories.

[SDK-4436] test: Migrate CI to GitHub Actions

---

.github/workflows/integration.yml
.husky/pre-commit

As we're using `pull_request_target` we need to specify the ref to checkout, also use `npx` to run pretty-quick in husky so that it doesn't need to be installed globally.
This is still going to fail as the issue at hand isn't fixed, but this will allow validating the fix in a PR
> Include any links supporting this change such as a:
>
> - GitHub Issue/PR number addressed or fixed
> - Auth0 Community post
> - StackOverflow post
> - Support forum thread
> - …

Checkout correct ref in integration tests

---

__mocks__/@auth0/auth0-spa-js.tsx
src/errors.tsx

For consistency, this PR makes OAuthError extend GenericError, which still extends Error.
#636

Make OAuthError extend GenericError

---

__mocks__/@auth0/auth0-spa-js.tsx
src/errors.tsx

Reverts auth0/auth0-react#638, because we still target ES5 and it broke things. Worth investigating, but can first revert.

Revert "Make OAuthError extend GenericError"

---

package-lock.json
package.json

Updates SPA-JS to the latest version to add support for workerUrl.
https://github.com/auth0/auth0-spa-js/releases/tag/v2.1.3

Update Auth0-SPA-JS to latest version

---

cypress/e2e/smoke.cy.ts
examples/cra-react-router/package.json
examples/gatsby-app/package.json

> Currently we are unable to merge any PR to the `main` because `integration test (CRA)` and `integration test (Gatsby)` are failing when the Github runs checks. This issue is caused by one of the sub-dependancy (`ajv`) update  in the example app `examples/cra-react-router`. The changes made in the pull-request serve as a temporary workaround rather than a definitive solution.
> Original issue; failing `Integration Tests / Run example tests (pull_request_target)`.
> With this PR changes, all the integration tests and workflow checks should get passed.

Workaround for failing "integration test (CRA)"

---

.github/workflows/npm-release.yml

fixes npm release workflow
releases were not happening because of wrong relative path to action files in `npm-release.yml` workflow file.

fix npm release workflow

---

.github/workflows/test.yml

- The artifact restoration step was removed from the dependency installation process in the test workflow.
- The dependency installation step now uses `pnpm install --frozen-lockfile` for efficiency.
- This change streamlines the dependency installation process.
- This change improves the efficiency of the CI/CD pipeline.
- The system impact is minimal, as only the test workflow is affected.
- There is no expected performance impact on the application itself.

refactor: streamline dependency installation by removing artifact restoration step

---

src/auth0-provider.tsx
src/reducer.tsx

- Enhanced type safety in `Auth0Provider` and its reducer by introducing a generic user type.
- Updated `Auth0ProviderOptions` interface to accept a generic user type.
- Modified the `onRedirectCallback` function to accept the generic user type.
- Updated the reducer function to handle the generic user type.
- The changes were tested by integrating them to a sample app and verifying with a generic user type
- Improved type safety for the `Auth0Provider` component and reducer.
- No changes to the functionality of the component are expected.
- No performance impact is anticipated.
- This PR addresses issue mentioned in https://github.com/auth0/auth0-react/issues/748

Enhance type safety in Auth0Provider and reducer by introducing generic user type

---

EXAMPLES.md
__mocks__/@auth0/auth0-spa-js.tsx
__tests__/auth-provider.test.tsx
package-lock.json
package.json
src/auth0-context.tsx
src/auth0-provider.tsx
src/index.tsx

This PR adds support for DPoP via an update of `auth0-spa-js` from 2.3.0 to 2.4.1.
New methods are exposed, docs are updated. No logic changes.

Add support for DPoP

---

EXAMPLES.md
package-lock.json
package.json

In this PR, `auth0-spa-js` has been updated to allow `auth0-react` to use [Multi-Resource Refresh Tokens (MRRT)](https://auth0.com/docs/secure/tokens/refresh-tokens/multi-resource-refresh-token). An example of configuring the Auth0Provider to use MRRT has also been provided.
- [Configure MRRT](https://auth0.com/docs/secure/tokens/refresh-tokens/multi-resource-refresh-token/configure-and-implement-multi-resource-refresh-token).
- In your react testing …

Implement MRRT
